apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - image: node-app:3.0
        # Set this property to pull image from local docker 
        # and block from public docker repo 
        imagePullPolicy: Never
        name: node-app
        resources: {}